'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditAccount

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMa_KH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMa_KH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtTEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTEN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCMND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCMND As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDIEN_THOAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDIEN_THOAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMAIL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSO_TAI_KHOAN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSO_TAI_KHOAN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNGAN_HANG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNGAN_HANG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBaoTro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBaoTro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCheckBaoTro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckBaoTro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTEN_BAO_TRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTEN_BAO_TRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMA_BAO_TRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMA_BAO_TRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnKichHoat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKichHoat As Global.System.Web.UI.WebControls.Button
End Class
