'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PackageUpgrade

    '''<summary>
    '''hidMA_CAY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMA_CAY As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtMA_KH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMA_KH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCheckMA_KH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckMA_KH As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTEN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlGOI_DAU_TU_HIEN_TAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGOI_DAU_TU_HIEN_TAI As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlGOI_DAU_TU_NANG_CAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGOI_DAU_TU_NANG_CAP As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtGHI_CHU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGHI_CHU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUpgrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpgrade As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsgPackageUpgrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgPackageUpgrade As Global.System.Web.UI.WebControls.Label
End Class
