'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AccountTreeView

    '''<summary>
    '''lblDOANH_SO_CA_NHAN_THANG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_CA_NHAN_THANG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_CA_NHAN_TICH_LUY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_CA_NHAN_TICH_LUY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_KET_CHUYEN_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_KET_CHUYEN_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_KET_CHUYEN_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_KET_CHUYEN_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_TICH_LUY_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_TICH_LUY_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_TICH_LUY_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_TICH_LUY_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTONG_SO_THANH_VIEN_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTONG_SO_THANH_VIEN_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTONG_SO_THANH_VIEN_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTONG_SO_THANH_VIEN_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSO_THANH_VIEN_MOI_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSO_THANH_VIEN_MOI_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSO_THANH_VIEN_MOI_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSO_THANH_VIEN_MOI_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSO_THANH_VIEN_MOI_BAO_TRO_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSO_THANH_VIEN_MOI_BAO_TRO_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSO_THANH_VIEN_MOI_BAO_TRO_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSO_THANH_VIEN_MOI_BAO_TRO_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMA_CAY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMA_CAY As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnShowSponsor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowSponsor As Global.System.Web.UI.WebControls.Button
End Class
