'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AccountCommisionDetail

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblDOANH_SO_CA_NHAN_THANG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_CA_NHAN_THANG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_CA_NHAN_TICH_LUY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_CA_NHAN_TICH_LUY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_KET_CHUYEN_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_KET_CHUYEN_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_KET_CHUYEN_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_KET_CHUYEN_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_TICH_LUY_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_TICH_LUY_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOANH_SO_TICH_LUY_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOANH_SO_TICH_LUY_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSO_THANH_VIEN_MOI_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSO_THANH_VIEN_MOI_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSO_THANH_VIEN_MOI_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSO_THANH_VIEN_MOI_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSO_THANH_VIEN_MOI_BAO_TRO_TRAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSO_THANH_VIEN_MOI_BAO_TRO_TRAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSO_THANH_VIEN_MOI_BAO_TRO_PHAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSO_THANH_VIEN_MOI_BAO_TRO_PHAI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHOA_HONG_TRUC_TIEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHOA_HONG_TRUC_TIEP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHOA_HONG_GIAN_TIEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHOA_HONG_GIAN_TIEP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHOA_HONG_CO_BAN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHOA_HONG_CO_BAN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHOA_HONG_CO_BAN_DUOC_TINH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHOA_HONG_CO_BAN_DUOC_TINH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQUY_TIEN_MAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQUY_TIEN_MAT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQUY_PHONG_CACH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQUY_PHONG_CACH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQUY_DAO_TAO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQUY_DAO_TAO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTONG_CONG_DOANH_SO_THANG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTONG_CONG_DOANH_SO_THANG As Global.System.Web.UI.WebControls.Label
End Class
