'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AccountCommisionCommit

    '''<summary>
    '''ddlMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnChotHoaHong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChotHoaHong As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlMonth_Chot_Lai_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMonth_Chot_Lai_DS As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnChotLaiHoaHong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChotLaiHoaHong As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblNotify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotify As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlMonthDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMonthDS As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTONG_SO_THANH_VIEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTONG_SO_THANH_VIEN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTONG_DOANH_SO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTONG_DOANH_SO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHOA_HONG_TRUC_TIEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHOA_HONG_TRUC_TIEP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHOA_HONG_GIAN_TIEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHOA_HONG_GIAN_TIEP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHOA_HONG_CO_BAN_DUOC_TINH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHOA_HONG_CO_BAN_DUOC_TINH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTHUONG_THANH_TICH_DUOC_TINH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTHUONG_THANH_TICH_DUOC_TINH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQUY_TIEN_MAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQUY_TIEN_MAT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQUY_PHONG_CACH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQUY_PHONG_CACH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQUY_DAO_TAO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQUY_DAO_TAO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTONG_CONG_DOANH_SO_THANG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTONG_CONG_DOANH_SO_THANG As Global.System.Web.UI.WebControls.Label
End Class
