'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusinessReport

    '''<summary>
    '''hidTypeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidTypeSearch As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlDanhHieu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDanhHieu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDanhHieu_THANG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDanhHieu_THANG As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSearchDanhHieu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchDanhHieu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlToanTuTrai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlToanTuTrai As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDoanhSoTrai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDoanhSoTrai As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlToanTuPhai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlToanTuPhai As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDoanhSoPhai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDoanhSoPhai As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlDoanhSo_THANG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDoanhSo_THANG As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSearch_DOANH_SO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch_DOANH_SO As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTuNgay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTuNgay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDenNgay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDenNgay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch_NGAY_THAM_GIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch_NGAY_THAM_GIA As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtMA_THANH_VIEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMA_THANH_VIEN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch_MA_THANH_VIEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch_MA_THANH_VIEN As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblNotify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotify As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''datagrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datagrid As Global.System.Web.UI.WebControls.GridView
End Class
