'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditInformation

    '''<summary>
    '''SuccessMessagePlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''setMAT_KHAU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents setMAT_KHAU As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''MAT_KHAU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MAT_KHAU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''confirmMAT_KHAU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmMAT_KHAU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''changeMAT_KHAUHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changeMAT_KHAUHolder As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''CurrentMAT_KHAULabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentMAT_KHAULabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CurrentMAT_KHAU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentMAT_KHAU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NewMAT_KHAULabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewMAT_KHAULabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewMAT_KHAU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewMAT_KHAU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ConfirmNewMAT_KHAULabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmNewMAT_KHAULabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ConfirmNewMAT_KHAU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmNewMAT_KHAU As Global.System.Web.UI.WebControls.TextBox
End Class
